
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/Applications/CMake.app/Contents/share/cmake-3.30/Modules/CMakeDetermineSystem.cmake:200 (message)"
      - "CMakeLists.txt:17 (project)"
    message: |
      The target system is: Generic -  - 
      The host system is: Darwin - 23.6.0 - arm64
  -
    kind: "message-v1"
    backtrace:
      - "/Applications/CMake.app/Contents/share/cmake-3.30/Modules/CMakeDetermineCompilerId.cmake:1205 (message)"
      - "/Applications/CMake.app/Contents/share/cmake-3.30/Modules/CMakeDetermineASMCompiler.cmake:135 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)"
      - "CMakeLists.txt:17 (project)"
    message: |
      Checking whether the ASM compiler is GNU using "--version" did not match "(GNU assembler)|(GCC)|(Free Software Foundation)":
      MPLAB XC8 PIC(R) Assembler V3.10
      Build date: Aug 13 2025
      Copyright (C) 2025 Microchip Technology Inc.
  -
    kind: "message-v1"
    backtrace:
      - "/Applications/CMake.app/Contents/share/cmake-3.30/Modules/CMakeDetermineCompilerId.cmake:1205 (message)"
      - "/Applications/CMake.app/Contents/share/cmake-3.30/Modules/CMakeDetermineASMCompiler.cmake:135 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)"
      - "CMakeLists.txt:17 (project)"
    message: |
      Checking whether the ASM compiler is AppleClang using "--version" did not match "(Apple (clang|LLVM) version)":
      MPLAB XC8 PIC(R) Assembler V3.10
      Build date: Aug 13 2025
      Copyright (C) 2025 Microchip Technology Inc.
  -
    kind: "message-v1"
    backtrace:
      - "/Applications/CMake.app/Contents/share/cmake-3.30/Modules/CMakeDetermineCompilerId.cmake:1205 (message)"
      - "/Applications/CMake.app/Contents/share/cmake-3.30/Modules/CMakeDetermineASMCompiler.cmake:135 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)"
      - "CMakeLists.txt:17 (project)"
    message: |
      Checking whether the ASM compiler is Clang using "--version" did not match "(clang version)":
      MPLAB XC8 PIC(R) Assembler V3.10
      Build date: Aug 13 2025
      Copyright (C) 2025 Microchip Technology Inc.
  -
    kind: "message-v1"
    backtrace:
      - "/Applications/CMake.app/Contents/share/cmake-3.30/Modules/CMakeDetermineCompilerId.cmake:1205 (message)"
      - "/Applications/CMake.app/Contents/share/cmake-3.30/Modules/CMakeDetermineASMCompiler.cmake:135 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)"
      - "CMakeLists.txt:17 (project)"
    message: |
      Checking whether the ASM compiler is ARMClang using "--version" did not match "armclang":
      MPLAB XC8 PIC(R) Assembler V3.10
      Build date: Aug 13 2025
      Copyright (C) 2025 Microchip Technology Inc.
  -
    kind: "message-v1"
    backtrace:
      - "/Applications/CMake.app/Contents/share/cmake-3.30/Modules/CMakeDetermineCompilerId.cmake:1205 (message)"
      - "/Applications/CMake.app/Contents/share/cmake-3.30/Modules/CMakeDetermineASMCompiler.cmake:135 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)"
      - "CMakeLists.txt:17 (project)"
    message: |
      Checking whether the ASM compiler is OrangeC using "--version" did not match "occ \\(OrangeC\\) Version":
      MPLAB XC8 PIC(R) Assembler V3.10
      Build date: Aug 13 2025
      Copyright (C) 2025 Microchip Technology Inc.
  -
    kind: "message-v1"
    backtrace:
      - "/Applications/CMake.app/Contents/share/cmake-3.30/Modules/CMakeDetermineCompilerId.cmake:1205 (message)"
      - "/Applications/CMake.app/Contents/share/cmake-3.30/Modules/CMakeDetermineASMCompiler.cmake:135 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)"
      - "CMakeLists.txt:17 (project)"
    message: |
      Checking whether the ASM compiler is HP using "-V" did not match "HP C":
      (2042) no target device specified; use the -mcpu option to specify a target device
  -
    kind: "message-v1"
    backtrace:
      - "/Applications/CMake.app/Contents/share/cmake-3.30/Modules/CMakeDetermineCompilerId.cmake:1205 (message)"
      - "/Applications/CMake.app/Contents/share/cmake-3.30/Modules/CMakeDetermineASMCompiler.cmake:135 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)"
      - "CMakeLists.txt:17 (project)"
    message: |
      Checking whether the ASM compiler is Intel using "--version" did not match "(ICC)":
      MPLAB XC8 PIC(R) Assembler V3.10
      Build date: Aug 13 2025
      Copyright (C) 2025 Microchip Technology Inc.
  -
    kind: "message-v1"
    backtrace:
      - "/Applications/CMake.app/Contents/share/cmake-3.30/Modules/CMakeDetermineCompilerId.cmake:1205 (message)"
      - "/Applications/CMake.app/Contents/share/cmake-3.30/Modules/CMakeDetermineASMCompiler.cmake:135 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)"
      - "CMakeLists.txt:17 (project)"
    message: |
      Checking whether the ASM compiler is IntelLLVM using "--version" did not match "(Intel[^
      ]+oneAPI)":
      MPLAB XC8 PIC(R) Assembler V3.10
      Build date: Aug 13 2025
      Copyright (C) 2025 Microchip Technology Inc.
  -
    kind: "message-v1"
    backtrace:
      - "/Applications/CMake.app/Contents/share/cmake-3.30/Modules/CMakeDetermineCompilerId.cmake:1205 (message)"
      - "/Applications/CMake.app/Contents/share/cmake-3.30/Modules/CMakeDetermineASMCompiler.cmake:135 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)"
      - "CMakeLists.txt:17 (project)"
    message: |
      Checking whether the ASM compiler is SunPro using "-V" did not match "Sun C":
      (2042) no target device specified; use the -mcpu option to specify a target device
  -
    kind: "message-v1"
    backtrace:
      - "/Applications/CMake.app/Contents/share/cmake-3.30/Modules/CMakeDetermineCompilerId.cmake:1205 (message)"
      - "/Applications/CMake.app/Contents/share/cmake-3.30/Modules/CMakeDetermineASMCompiler.cmake:135 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)"
      - "CMakeLists.txt:17 (project)"
    message: |
      Checking whether the ASM compiler is XL using "-qversion" did not match "XL C":
      (2042) no target device specified; use the -mcpu option to specify a target device
  -
    kind: "message-v1"
    backtrace:
      - "/Applications/CMake.app/Contents/share/cmake-3.30/Modules/CMakeDetermineCompilerId.cmake:1205 (message)"
      - "/Applications/CMake.app/Contents/share/cmake-3.30/Modules/CMakeDetermineASMCompiler.cmake:135 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)"
      - "CMakeLists.txt:17 (project)"
    message: |
      Checking whether the ASM compiler is MSVC using "-?" did not match "Microsoft":
      (2042) no target device specified; use the -mcpu option to specify a target device
  -
    kind: "message-v1"
    backtrace:
      - "/Applications/CMake.app/Contents/share/cmake-3.30/Modules/CMakeDetermineCompilerId.cmake:1205 (message)"
      - "/Applications/CMake.app/Contents/share/cmake-3.30/Modules/CMakeDetermineASMCompiler.cmake:135 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)"
      - "CMakeLists.txt:17 (project)"
    message: |
      Checking whether the ASM compiler is TI using "-h" did not match "Texas Instruments":
      (2042) no target device specified; use the -mcpu option to specify a target device
  -
    kind: "message-v1"
    backtrace:
      - "/Applications/CMake.app/Contents/share/cmake-3.30/Modules/CMakeDetermineCompilerId.cmake:1205 (message)"
      - "/Applications/CMake.app/Contents/share/cmake-3.30/Modules/CMakeDetermineASMCompiler.cmake:135 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)"
      - "CMakeLists.txt:17 (project)"
    message: |
      Checking whether the ASM compiler is TIClang using "--version" did not match "(TI (.*) Clang Compiler)":
      MPLAB XC8 PIC(R) Assembler V3.10
      Build date: Aug 13 2025
      Copyright (C) 2025 Microchip Technology Inc.
  -
    kind: "message-v1"
    backtrace:
      - "/Applications/CMake.app/Contents/share/cmake-3.30/Modules/CMakeDetermineCompilerId.cmake:1205 (message)"
      - "/Applications/CMake.app/Contents/share/cmake-3.30/Modules/CMakeDetermineASMCompiler.cmake:135 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)"
      - "CMakeLists.txt:17 (project)"
    message: |
      Checking whether the ASM compiler is IAR using "" did not match "IAR Assembler":
      (2042) no target device specified; use the -mcpu option to specify a target device
  -
    kind: "message-v1"
    backtrace:
      - "/Applications/CMake.app/Contents/share/cmake-3.30/Modules/CMakeDetermineCompilerId.cmake:1205 (message)"
      - "/Applications/CMake.app/Contents/share/cmake-3.30/Modules/CMakeDetermineASMCompiler.cmake:135 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)"
      - "CMakeLists.txt:17 (project)"
    message: |
      Checking whether the ASM compiler is ARMCC using "" did not match "(ARM Compiler)|(ARM Assembler)|(Arm Compiler)":
      (2042) no target device specified; use the -mcpu option to specify a target device
  -
    kind: "message-v1"
    backtrace:
      - "/Applications/CMake.app/Contents/share/cmake-3.30/Modules/CMakeDetermineCompilerId.cmake:1205 (message)"
      - "/Applications/CMake.app/Contents/share/cmake-3.30/Modules/CMakeDetermineASMCompiler.cmake:135 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)"
      - "CMakeLists.txt:17 (project)"
    message: |
      Checking whether the ASM compiler is NASM using "-v" did not match "(NASM version)":
      (2042) no target device specified; use the -mcpu option to specify a target device
  -
    kind: "message-v1"
    backtrace:
      - "/Applications/CMake.app/Contents/share/cmake-3.30/Modules/CMakeDetermineCompilerId.cmake:1205 (message)"
      - "/Applications/CMake.app/Contents/share/cmake-3.30/Modules/CMakeDetermineASMCompiler.cmake:135 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)"
      - "CMakeLists.txt:17 (project)"
    message: |
      Checking whether the ASM compiler is YASM using "--version" did not match "(yasm)":
      MPLAB XC8 PIC(R) Assembler V3.10
      Build date: Aug 13 2025
      Copyright (C) 2025 Microchip Technology Inc.
  -
    kind: "message-v1"
    backtrace:
      - "/Applications/CMake.app/Contents/share/cmake-3.30/Modules/CMakeDetermineCompilerId.cmake:1205 (message)"
      - "/Applications/CMake.app/Contents/share/cmake-3.30/Modules/CMakeDetermineASMCompiler.cmake:135 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)"
      - "CMakeLists.txt:17 (project)"
    message: |
      Checking whether the ASM compiler is ADSP using "-version" did not match "Analog Devices":
      (2042) no target device specified; use the -mcpu option to specify a target device
  -
    kind: "message-v1"
    backtrace:
      - "/Applications/CMake.app/Contents/share/cmake-3.30/Modules/CMakeDetermineCompilerId.cmake:1205 (message)"
      - "/Applications/CMake.app/Contents/share/cmake-3.30/Modules/CMakeDetermineASMCompiler.cmake:135 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)"
      - "CMakeLists.txt:17 (project)"
    message: |
      Checking whether the ASM compiler is QCC using "-V" did not match "gcc_nto":
      (2042) no target device specified; use the -mcpu option to specify a target device
...
